config/routes.rb
Rails.application.routes.draw do
  get 'search/results'
	require 'sidekiq/web'
  mount Sidekiq::Web,     at: '/sidekiq' #, constraints: AdminConstraint.new
  mount ImageUploader.upload_endpoint(:cache) => '/images/cache'
  mount ImageUploader.upload_endpoint(:store) => '/images/store'
  mount FileUploader.upload_endpoint(:cache) => '/file/cache'
  mount FileUploader.upload_endpoint(:store) => '/file/store'

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    get 'supersecretinvitelink', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/@:username', to: 'users#show', as: :short_user
  get '/@:username/:id', to: 'posts#show', as: :short_user_post

  # resources :users, param: :username, path: '/', only: :show do
  resources :users do
    get :index
    member do
      post :remove_avatar
      post :follow
      post :unfollow
    end
  end

  resources :uploads do
    get :extract_images
	end

  resources :posts do
    resources :tags
    get :suggested_tags
  end

  resources :projects do
    post :tags, only: [:create, :destroy]
  end

  resources :tags

  namespace :search do
    get :results
    get :bar
  end

	post '/file', to: 'uploads#file'
  post '/posts/add_figure', to: 'posts#add_figure'
  get '/write', to: 'posts#write'

  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'dashboard', to: 'pages#dashboard'

  get 'admin', to: 'pages#admin'
  get 'pricing', to: 'pages#pricing'
  get 'internship', to: 'pages#jobs'

  namespace :admin, module: 'admin' do
    resources :users
    resources :posts
    resources :uploads
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  if Rails.env.development?
    resource :styleguide, controller: :styleguide, only: :show
  end

  root to: "pages#index"
end

app/views/shared/_flash_notices.html.slim
- flash.each do | key, value |
	#flash-container
		.container
			.flash.animated.fadeInDown class=key
				= value

app/views/shared/_footer.html.slim
.footer.mt-5
	= link_to root_path do
		.back_to_home
  		= image_tag 'jelly.png'

    .links
      span.mr-3.ml-3 © 2020 Jelly PBC
      = link_to "About", about_path, class: "mr-3 ml-3"
      = link_to "Terms", terms_path, class: "mr-3 ml-3"
      = link_to "Blog", "https://jellypbc.com", class: "mr-3 ml-3"

app/views/shared/_nav.html.slim
- opts ||= opts
- white_nav ||= @white_nav

nav.navbar.navbar-expand-lg id="#{opts[:id] if opts}" class="#{'white-nav' if white_nav} #{opts[:class] if opts}"
  .container.my-0

    = link_to root_path, class: "navbar-brand" do
      = image_tag 'jelly.png'

    button.navbar-toggler type="button" data-toggle="collapse" data-target="#menu" aria-controls="menu" aria-expanded="false" aria-label="Toggle navigation"
      - if current_user
        .avatar-clip
          = image_tag current_user.avatar_url(:small), class: "avatar"
      - else
        i.fa.fa-stream

    #menu.collapse.navbar-collapse
      = react_component 'SearchBar'

      = form_tag(search_results_path, method: :get, id: 'search-fallback', class: "form-inline my-2 my-lg-0")
        = text_field_tag :query, nil, placeholder: "Search", type: "search", 'aria-label'=>'Search'

      ul.subnav.ml-auto
        - if current_user

          - if @post
            li.nav-item.mr-3
              = link_to 'Save as draft', write_path, class: "btn btn-outline-dark btn-sm"
            li.nav-item.mr-3
              = link_to 'Publish', write_path, class: "btn btn-primary btn-sm"
          - else
            li.nav-item
              = link_to 'Write', write_path, class: "nav-link"
            li.nav-item
              = link_to 'Upload a PDF', new_upload_path, class: "nav-link"

          li.nav-item.dropdown
            a.dropdown-toggle.avatar-link href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
              .avatar-clip
                = avatar_image_tag current_user, :medium, class: "avatar"

            .dropdown-menu.dropdown-menu-right
              a.dropdown-item href=dashboard_path
                | Dashboard
              a.dropdown-item href=short_user_path(current_user)
                | Profile
              a.dropdown-item href=edit_user_path(current_user)
                | Settings
              hr
              = link_to 'Log Out', destroy_user_session_path, method: :delete, class:"dropdown-item"
              - if current_user.admin?
                hr
                a.dropdown-item href=admin_path
                  | Admin


        - else
          li.nav-item.mr-0
            = link_to 'Log In', new_user_session_path, class: "nav-link"