config/routes.rb
Rails.application.routes.draw do
  get 'search/results'
	require 'sidekiq/web'
  mount Sidekiq::Web,     at: '/sidekiq' #, constraints: AdminConstraint.new
  mount ImageUploader.upload_endpoint(:cache) => '/images/cache'
  mount ImageUploader.upload_endpoint(:store) => '/images/store'
  mount FileUploader.upload_endpoint(:cache) => '/file/cache'
  mount FileUploader.upload_endpoint(:store) => '/file/store'

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    get 'supersecretinvitelink', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/@:username', to: 'users#show', as: :short_user
  get '/@:username/:id', to: 'posts#show', as: :short_user_post

  # resources :users, param: :username, path: '/', only: :show do
  resources :users do
    get :index
    member do
      post :remove_avatar
      post :follow
      post :unfollow
    end
  end

  resources :uploads do
    get :extract_images
	end

  resources :posts do
    resources :tags
    get :suggested_tags
  end

  resources :projects do
    post :tags, only: [:create, :destroy]
  end

  resources :tags

  namespace :search do
    get :results
    get :bar
  end

	post '/file', to: 'uploads#file'
  post '/posts/add_figure', to: 'posts#add_figure'
  get '/write', to: 'posts#write'

  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'dashboard', to: 'pages#dashboard'

  get 'admin', to: 'pages#admin'
  get 'pricing', to: 'pages#pricing'
  get 'internship', to: 'pages#jobs'

  namespace :admin, module: 'admin' do
    resources :users
    resources :posts
    resources :uploads
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  if Rails.env.development?
    resource :styleguide, controller: :styleguide, only: :show
  end

  root to: "pages#index"
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id           :bigint           not null, primary key
#  description  :text
#  munged_title :string
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Project < ApplicationRecord
  BLACKLIST = %w(new edit destroy update posts post)

  validates :munged_title, presence: true, uniqueness: { case_sensitive: false }
  validate :allowed_slug

  has_many :tags, as: :taggable

  # Project.create
  before_validation :set_placeholder_slug, on: :create
  before_save :set_munged_title!

  def to_param
    munged_title
  end

  def set_placeholder_slug
    unless read_attribute(:munged_title)
      placeholder = (0...6).map{(65+rand(26)).chr}.join.downcase
      write_attribute :munged_title, placeholder
    end
  end

  def allowed_slug
    if BLACKLIST.include? send(:munged_title)
      errors.add :munged_title, 'This slug is unavailable'
    end
  end

  def set_munged_title!
    write_attribute :munged_title, generate_munged_title
  end

  def generate_munged_title
    pending_munged_title = ActionController::Base.helpers.strip_tags(title).parameterize
    if Project.where("munged_title=?", pending_munged_title).any?
      sequence = self.class.where("munged_title like '#{pending_munged_title}-%'").count + 2
      pending_munged_title = "#{pending_munged_title}-#{sequence}"
    end
    pending_munged_title
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.order(created_at: :desc)
      .paginate(page: params[:page], per_page: 40)
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      id_or_munged_title = params[:munged_title] || params[:id] || params[:project_id]
      @project ||= begin
        Project.find_by! munged_title: id_or_munged_title
      rescue ActiveRecord::RecordNotFound => e
        Project.find id_or_munged_title
      end
    end

    def project_params
      params.require(:project).permit(
        :title, :munged_title, :description
      )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.slim
= form_for @project do |form|
  - if @project.errors.any?
    #error_explanation
      h2
        = pluralize(project.errors.count, "error")
        | prohibited this project from being saved:

      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field
    = form.label :title
    = form.text_field :title

  .field
    = form.label :description
    = form.text_area :description

  .actions.my-4
    - button_text = @project.id ? "Save Project" : "Create Project"
    = form.submit button_text, class: "btn btn-primary"

    span.divider.mx-3 |
    = link_to "Back", projects_path

app/views/projects/edit.html.slim
.container
  .row
    .col-md-12
      h4 Edit Project
      h1 = @project.title

      = render "form", project: @project

app/views/projects/index.html.slim
.container
  .row
    .col-md-12
      h1 Index

      table.table
        thead
          th ID
          th Title
          th Munged Title
          th Description
          th
          th
          th

        - @projects.each do |project|
          tr
            td = project.id
            td = project.title
            td = project.munged_title
            td = project.description
            td = link_to "Show", project
            td = link_to "Edit", edit_project_path(project)
            td = link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

      br
      = link_to "New Project", new_project_path, class: "btn btn-primary"

      = will_paginate @projects

app/views/projects/new.html.slim
.container
  h1 New Project

  .row
    .col-md-12
      .form.form-group
        = render 'form', project: @project

app/views/projects/show.html.slim
.container
  .row
    .col-md-12
      h1 = @project.title
      h4 description
      p = @project.description
      h4 title
      p = @project.munged_title

      - if current_user && user_is_admin?
        = link_to "Edit Project", edit_project_path

        span.divider.mx-3 |

        = link_to "View all projects", projects_path