config/routes.rb
Rails.application.routes.draw do
  get 'search/results'
	require 'sidekiq/web'
  mount Sidekiq::Web,     at: '/sidekiq' #, constraints: AdminConstraint.new
  mount ImageUploader.upload_endpoint(:cache) => '/images/cache'
  mount ImageUploader.upload_endpoint(:store) => '/images/store'
  mount FileUploader.upload_endpoint(:cache) => '/file/cache'
  mount FileUploader.upload_endpoint(:store) => '/file/store'

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    get 'supersecretinvitelink', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/@:username', to: 'users#show', as: :short_user
  get '/@:username/:id', to: 'posts#show', as: :short_user_post

  # resources :users, param: :username, path: '/', only: :show do
  resources :users do
    get :index
    member do
      post :remove_avatar
      post :follow
      post :unfollow
    end
  end

  resources :uploads do
    get :extract_images
	end

  resources :posts do
    resources :tags
    get :suggested_tags
  end

  resources :projects do
    post :tags, only: [:create, :destroy]
  end

  resources :tags

  namespace :search do
    get :results
    get :bar
  end

	post '/file', to: 'uploads#file'
  post '/posts/add_figure', to: 'posts#add_figure'
  get '/write', to: 'posts#write'

  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'dashboard', to: 'pages#dashboard'

  get 'admin', to: 'pages#admin'
  get 'pricing', to: 'pages#pricing'
  get 'internship', to: 'pages#jobs'

  namespace :admin, module: 'admin' do
    resources :users
    resources :posts
    resources :uploads
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  if Rails.env.development?
    resource :styleguide, controller: :styleguide, only: :show
  end

  root to: "pages#index"
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id            :bigint           not null, primary key
#  color         :string
#  slug          :string
#  taggable_type :string
#  text          :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  taggable_id   :integer
#

class Tag < ApplicationRecord
  belongs_to :taggable, polymorphic: true, optional: true

  # validates :slug, presence: true, uniqueness: { case_sensitive: false }

  before_validation :check_and_set_slug

  # def to_param
  #   slug
  # end

  private

    def check_and_set_slug
      self.slug = text.parameterize if self.slug.blank?
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :set_taggable, only: [:show, :create, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def show
    @posts = @tag.posts
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      @target.tags << @tag
      respond_to do |format|
        format.html { head :ok }
        format.json { render json: TagSerializer.new(@tag).serializable_hash, status: :ok }
      end
    else
      respond_to do |format|
        head :bad_request
      end
    end
  end

  def update
    # binding.pry
    respond_to do |format|
      if @target.tags << @tag
        format.json { render json: TagSerializer.new(@tag).serializable_hash, status: :ok }
      else
        head :bad_request
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { head :ok }
      format.json { head :ok }
    end
  end

  private
    def set_tag
      id_or_slug = tag_params[:slug] || tag_params[:id]
      @tag ||= begin
        Tag.find_by! slug: id_or_slug.parameterize
      rescue ActiveRecord::RecordNotFound => e
        Tag.find id_or_slug
      end
    end

    def set_taggable
      klass = tag_params[:taggable_type].titleize.constantize
      @target = klass.find tag_params[:taggable_id]
    end

    def tag_params
      params.require(:tag).permit(
        :id, :text, :slug, :taggable_id, :taggable_type
      )
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :posts %>
    <%= form.text_field :posts %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.text %></td>
        <td><%= tag.slug %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @tag.text %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @tag.slug %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>