config/routes.rb
Rails.application.routes.draw do
  get 'search/results'
	require 'sidekiq/web'
  mount Sidekiq::Web,     at: '/sidekiq' #, constraints: AdminConstraint.new
  mount ImageUploader.upload_endpoint(:cache) => '/images/cache'
  mount ImageUploader.upload_endpoint(:store) => '/images/store'
  mount FileUploader.upload_endpoint(:cache) => '/file/cache'
  mount FileUploader.upload_endpoint(:store) => '/file/store'

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    get 'supersecretinvitelink', to: 'devise/registrations#new'
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/@:username', to: 'users#show', as: :short_user
  get '/@:username/:id', to: 'posts#show', as: :short_user_post

  # resources :users, param: :username, path: '/', only: :show do
  resources :users do
    get :index
    member do
      post :remove_avatar
      post :follow
      post :unfollow
    end
  end

  resources :uploads do
    get :extract_images
	end

  resources :posts do
    resources :tags
    get :suggested_tags
  end

  resources :projects do
    post :tags, only: [:create, :destroy]
  end

  resources :tags

  namespace :search do
    get :results
    get :bar
  end

	post '/file', to: 'uploads#file'
  post '/posts/add_figure', to: 'posts#add_figure'
  get '/write', to: 'posts#write'

  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'dashboard', to: 'pages#dashboard'

  get 'admin', to: 'pages#admin'
  get 'pricing', to: 'pages#pricing'
  get 'internship', to: 'pages#jobs'

  namespace :admin, module: 'admin' do
    resources :users
    resources :posts
    resources :uploads
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  if Rails.env.development?
    resource :styleguide, controller: :styleguide, only: :show
  end

  root to: "pages#index"
end

app/models/upload.rb
# == Schema Information
#
# Table name: uploads
#
#  id         :bigint           not null, primary key
#  file_data  :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer
#  user_id    :integer
#
# Indexes
#
#  index_uploads_on_post_id  (post_id)
#  index_uploads_on_user_id  (user_id)
#

class Upload < ApplicationRecord
	include FileUploader::Attachment(:file)

	belongs_to :post, optional: true
  belongs_to :user, optional: true

	has_one :upload_tei, dependent: :destroy
	has_many :upload_figures, dependent: :destroy

	accepts_nested_attributes_for :upload_figures, allow_destroy: true

	validates_presence_of :file

	after_create_commit :process

	def process
    if is_pdf?
      create_upload_tei
      UploadParsePipelineWorker.perform_async(id)
    end
	end

	def is_pdf?
		file.metadata["mime_type"].include?("pdf")
	end

	def file_url
		url = file.url
		if Rails.env.development?
			if ENV['FIGURE_HOST']
				"http://rails:3000" + url
			else
				"http://host.docker.internal:3000" + url
			end
		else
			url
		end
	end

end

app/controllers/admin/uploads_controller.rb
module Admin
  class UploadsController < ApplicationController
    before_action :admin_only

    def show
    end

    def index
      @uploads = Upload.order(created_at: :desc)
        .paginate(page: params[:page], per_page: 30)
    end

    private

      def fetch_user
        @user = User.find_by_username(params[:id] || params[:user_id] || params[:username])
      end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [
    :show, :edit, :update, :destroy, :extract_images
  ]
  # skip_before_filter :verify_authenticity_token, only: [:file]
  protect_from_forgery except: :file

  def index
    @uploads = Upload.order(created_at: :desc)
      .paginate(page: params[:page], per_page: 30)
  end

  def show
  end

  def new
    @upload = Upload.new
  end

  def edit
  end

  def create
    if current_user
      @upload = current_user.uploads.new(upload_params)
      @post = current_user.posts.create!
      @upload.post = @post
    else
      @upload = Upload.new(upload_params)
      @post = Post.create!
      @upload.post = @post
    end

    respond_to do |format|
      if @upload.save!
        format.html { redirect_to @upload.post, notice: 'Upload was successfully created. Please refresh the page!' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def file
    if current_user
      @post = current_user.posts.new
      @upload = current_user.uploads.new
      @upload.post = @post
    else
      @post = Post.new
    	@upload = Upload.new
      @upload.post = @post
    end

    if params[:file_id]
			file = Shrine.uploaded_file(storage: :store, id: params[:file_id])
			file.refresh_metadata!
			@upload.file_attacher.set(file)
		end

    respond_to do |format|
      if @upload.save!
        redirect = current_user.present? ? short_user_post_path(current_user, @upload.post) : post_path(@upload.post)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render json: { redirect_to: redirect }, status: :ok, notice: "hooray" }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def extract_images
    FiguresExtractService.extract(@upload.id)
    redirect_to upload_path(@upload), notice: "Queued upload for figure extraction"
  end

  private
    def set_upload
      @upload ||= begin
        Upload.find(params[:id] || params[:upload_id])
      rescue ActiveRecord::RecordNotFound => e
        raise e
      end
    end

    def upload_params
      params.require(:upload).permit(:file, :user).to_h
    end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.slim
= form_with model: upload, local: true, html: {id: "form"} do |form|
  - if upload.errors.any?
    #error_explanation
      h2 #{pluralize(upload.errors.count, "error")} prohibited this upload from being saved:

      ul
        - upload.errors.full_messages.each do |message|
          li = message

  = form.hidden_field :file, value: upload.cached_file_data

  .input-group.my-4
    .custom-file
      = form.file_field :file, type: "file", required: true, class:"custom-file-input", id: "inputFile"

      label class="custom-file-label"  id="label" for="inputFile"
        | Choose file

  .actions.my-3
    = form.submit "Submit", class: 'btn btn-primary'

javascript:
  document.getElementById('inputFile')
    .addEventListener("change", function(){
      var fileName = document.getElementById('inputFile').files[0].name
      document.getElementById('label').textContent = fileName;
    });

app/views/uploads/_upload.html.slim
tr
  td = upload.id
  td
    - if upload.file && upload.file.metadata['mime_type']
      - if upload.file.metadata["mime_type"].include?("image")
        = link_to upload.file_url do
          i.fa.fa-image

      - elsif upload.file.metadata["mime_type"].include?("pdf")
        = link_to upload.file_url do
          i.fa.fa-book

  td = upload.file.metadata['filename'].html_safe if upload.file && upload.file.metadata['filename']
  td = upload.file.metadata['mime_type'] if upload.file && upload.file.metadata['mime_type']
  td
    - if Time.now - upload.created_at > 1.day
      = upload.created_at.strftime("%b %e, %l:%M %p")
    - else
      = time_ago_in_words(upload.created_at) + " ago"
  td = link_to 'Show', upload
  td = link_to 'Edit', edit_upload_path(upload)
  td = link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' }

app/views/uploads/edit.html.slim
.container.my-5
	.row
		.col-md-12
			h1 Editing Upload

			= render 'form', upload: @upload

			= link_to 'Show', @upload
			br
			|
			= link_to 'Back', uploads_path

app/views/uploads/index.html.slim
.container
	.row.mt-5
	  .col-md-12
	    h1 Uploads

	    = link_to 'New Upload', new_upload_path, class: 'btn btn-outline-dark my-3'

	    table.table.table-hover
	      thead
	        tr
	          th ID
	          th Link
	          th Filename
	          th Type
	          th Created
	          th Actions
	          th
	          th

	      tbody
	        - @uploads.each do |upload|
	        	= render 'upload', upload: upload

	    = will_paginate @uploads

app/views/uploads/new.html.slim
.container
	.row.mt-5
		.col-md-12
			h1 New Upload

			.mt-5
				= react_component "FileUploader", url: "/file"

			.mt-5
				= link_to 'Back', root_path

app/views/uploads/show.html.slim
.container
	.row.mt-5
		.col-md-12
			h1 Upload ID
			p = @upload.id

			br

			h2 File
			- if @upload.file
				- if @upload.file.metadata["mime_type"].include?("image")
					= image_tag @upload.file_url
				- elsif @upload.file.metadata["mime_type"].include?("pdf")
					p
						| File URL:
						= link_to @upload.file_url do
							span.ml-3
								i.fa.fa-book
								|&nbsp;#{@upload.file.metadata["filename"]}

			- @doc = Nokogiri::XML(@upload.upload_tei.body)
			- @bib = @doc.css("biblStruct[@type='array']")

			br

			- if @upload.post
				= link_to "View post", post_path(@upload.post)

			hr.my-5

			h2 Images
			= link_to "Extract images", upload_extract_images_path(id: @upload.id, upload_id: @upload.id)
			/ = link_to "Extract images", @upload, upload_extract_images_path, method: :post, confirm: "This will delete existing images, are you sure?", class: "btn btn-sm btn-danger"
			- if @upload.upload_figures
				- @upload.upload_figures.each do |image|
					.image.my-3
						= image_tag image.image.url if image.image

			hr.my-5

			h2 Debug
			a data-toggle="collapse" href="#collapse-debug" role="button" aria-expanded="false" aria-controls="collapse-debug"
				| Show full upload_tei
			#collapse-debug.markup.collapse
				= @doc.to_xml

			hr.my-5

			h2 Citations
			br

			- @doc.css("biblStruct[@type='array']").children.css('biblStruct').each_with_index do |biblStruct, index|
					h3 Citation ID: #{biblStruct.css('id').inner_html}
					.reference.my-4

						strong Title:
						p = biblStruct.css('title').css('__content__').inner_html

						strong Authors:
						- authors = biblStruct.css("persName")
						- author_list = []
						- authors.map do |author|
							- first = author.css("forename __content__").map{|a| a.inner_html}.join(" ")
							- last = author.css("surname").inner_html
							- full = []
							- full << first if first.present?
							- full << last if last.present?
							- full = full.join(" ")
							- author_list << full
				  	p = author_list.join(", ")

					.my-4
						a data-toggle="collapse" href="#collapse-#{index}" role="button" aria-expanded="false" aria-controls="collapse-#{index}"
							| Show raw
						.markup.collapse id="collapse-#{index}"
							.markup = biblStruct.inner_html
					hr.my-5

			= link_to 'Edit', edit_upload_path(@upload)
			br
			= link_to 'Back', uploads_path